[feature_param]
col_key = ['shop_id','goods_id']
col_qty = 'qty'
filter_func = "{'col_gtz_agg_days': (['mean', 'sum'], [2, 3])}"
col_time = "sdt"
col_partition = "dt"
conn = 'and'
sdate = ''
edate = ''
input_table = 'ai_dm.poc_data_test'
input_stock_table = 'ai_dm.poc_stock'
output_table = 'ai_dm.poc_data_test_out'