[lightgbm]
boosting_type='gbdt'
objective='regression'
importance_type='gain'
n_jobs=8
subsample=0.5
learning_rate=0.05
n_estimators=50
random_seed=1
metric='mae'#评估函数
feature_fraction=0.7 #建树的特征选择比例
max_depth=8
reg_alpha=0.001

[xgboost]
max_depth=3
n_estimators=100
learning_rate=0.01
random_state=42
seed=42
subsample=0.75
colsample_bytree=0.75
reg_lambda=1
gamma=1