[data]
table_sku_group='ai_dm_dev.ss_aip_model_selection_grouping'#分类分组结果表
ts_model_list=['lightgbm']
table_feat_y='ai_dm_dev.ss_aip_sales_boxcox'#y值表
table_feat_x='ai_dm_dev.ss_aip_features_all'

cols_sku_grouping=['shop_id','goods_id','apply_model','group_category']
apply_model='apply_model'
y_type='y_type'
sample_join_key_feat=['shop_id','goods_id','dt']
cols_feat_y_columns=['th_y']#对应的y值
cols_feat_x_columns=['th_y_gtz_mean_2d','th_y_hb_2d','week','week_day','is_holiday','aqi']#模型使用特征
sample_join_key_grouping=['shop_id','goods_id']#与分类分组表join的key
time_col='dt'#表示时间的的列，例如：dt，周和月有可能不用这个表示
sdate=''#样本开始日期
edate=''#样本结束日期