[data]
table_sku_group='ai_dm_dev.model_selection_grouping_table_0620'#分类分组结果表
ts_model_list=['Integrated']
table_feat_y='ai_dm_dev.no_sales_adjust_0620'#y值表
table_feat_x='ai_dm_dev.feat_shop_goods_dt'
y_type_list=['c']
cols_sku_grouping=['shop_id','y_type','apply_model','group_category']
apply_model='apply_model'
y_type='y_type'
sample_join_key_feat=['shop_id','goods_id','y_type','dt']
cols_feat_y_columns=['y']#对应的y值
cols_feat_x_columns=['max_qty_2','avg_qty_2']#模型使用特征
sample_join_key_grouping=['shop_id','goods_id']#与分类分组表join的key
time_col='dt'#表示时间的的列，例如：dt，周和月有可能不用这个表示
sdate=''#样本开始日期
edate=''#样本结束日期