[default]
mode_type='sp'
time_type='day'#day/week/month
y='y'#y的类型
save_table_cols=['shop_id','goods_id','apply_model','time_type','pred_time','y_pred']
hdfs_path='/user/liguoqiang/model'#模型存放地址

[result_processing_param]
is_write=true
write_type='hive'
mode_type='overwrite'
partition=[]
table_name='ai_dm.statistic_model_result'
file_path='file_path'
repartition=1
encoding='utf-8'
header=true
location='hdfs'