[basic]
time_col='dt'
master_key_cols=['shop_id','goods_id','y_type']#对应的主键
table_master='ai_dm_dev.io_daily_y'#主表
item='ibs_replenish.item'#item表
item_key_cols=['goods_id']#item表中对应的主键
table_biz_dt='ai_dm.ibs_biz_dt'#时间表
biz_dt_cols=['calmonth']#需要实现表中的列

[sales_data]
feat_y='ai_dm_dev.feat_y'
y_type_col='y_type'
y_type_value='c'
y_col='y'
edate=''
sdate=''