[default]
bound_cols=['storage_life','sale_days']#storage_life:保质期,sale_days:销售期
method_cols=['sale_classify']#销售分类
label_cols=['standard']#是否标品
model_selection_condition=["{'lightgbm':[{'storage_life':'(180,]','sale_classify':'normal'}]}",
"{'holt-winter':[{'standard':'1','storage_life':'[30,180]'},{'storage_life':'[1,1]'}]}"
]
default_model='dms'
method_key_cols=['shop_id','goods_id']#方法用的主键
mode_type='sp

[result_processing_param]
is_write=true
write_type='hive'
mode_type='overwrite'
partition=[]
table_name='ai_dm.ibs_sku_group_model_new'#结果存表
file_path='/tmp'
repartition=1
encoding='utf-8'
header=true
location='hdfs'