[params_data_prepare]
method = ['item_config','sales_classfify']#获取配置信息的方法
col_key = ['shop_id','goods_id']#商品分类所用的主字段
shop_list = ['1004','1228']#门店列表
col_bound = ['storage_life','sale_period']
col_label = ['standard','sku_category','is_new']
config_columns = ['storage_life','sale_period','standard','is_new','sale_days']
w_tail=3
w_ls=90
threshold_count=1
threshold_proportion=0.15
threshold_sales=14
col_time = 'sdt'
col_qty = 'th_y'
col_sku_category = ['sales_category','qty_avg'] #sku分类字段
item_config_table = "f'{db_dev}.{pre_table_name}_item_config'"
sales_table = "f'{db_dev}.{pre_table_name}_sales_boxcox'"
goods_class_table ="f'{db_dev}.{pre_table_name}_goods_class'"
config_tables = ["f'{db_dev}.{pre_table_name}_item_config'","f'{db_dev}.{pre_table_name}_sales_classify'"]
mode_type='sp'

[model_selection]
model_selection_condition= ["{'lightgbm':[{'storage_life':'(180,]','sales_category':'normal','is_new':'0'},{'standard':'1','sale_period':'[10,60]','sales_category':'normal','is_new':'0'}]}","{'holt-winter':[{'standard':'1','storage_life':'[30,180]'},{'storage_life':'[1,1]'}]}"]
col_selection = ['standard','sales_category','is_new','storage_life','sale_period','qty_avg']
col_bound = ['storage_life','sale_period']
col_label = ['standard','sales_category','is_new']
col_key = ['shop_id','goods_id']
default_model='DMS'
col_apply_model = 'apply_model'
model_selection_table = "f'{db_dev}.{pre_table_name}_model_selection'"

[model_grouping]
col_key = ['shop_id','goods_id']
col_apply_model = 'apply_model' #model列名
isometric_label ='isometric_group' #等距组名
frequency_label = 'frequency_group'#等频
label_label = 'label_group'#label列
group_label = 'group_category' #最终的组别名
shop_list = ['1004','1228']
group_nums = 20
partition_values = ['task_id','shop_id']
model_selection_table = "f'{db_dev}.{pre_table_name}_model_selection'"
model_grouping_table = "f'{db_dev}.{pre_table_name}_model_selection_grouping'"
group_condition = ["{'lightgbm':[{'isometric':{'group_nums':20,'col_partition':['shop_id'],'col_orderby':['qty_avg']}}]}","{'holtwinter':[{'equal_frequency':{'storage_life':[10,30,50],'sale_period':[40,90,10]}},{'col_labels':['shop_id','sales_category']}]}"]
