selects:
  - column: aip.table_1.aaaa
    as: aaaa
  - column: aip.table_2.bbb
    as: bbb
  - column: aip.table_3.cccc
    as: ccc
tables:
  drive: aip.table1
  driven:
    - aip.table2
    - aip.table3
where: aaaa = 1 and bbbb = 2 and ccc != 3 and aip.table_1.ddd > 0
dt:
  start: 2022-01-01
  end: 2022-08-08
