[holt-winter]
seasonal_periods=7
trend='add'
seasonal='add'
damped_trend=true
use_boxcox=false
initialization_method='estimated'
missing='drop'
freq='D'

[arima]
start_p=1
start_q=1
max_p=3
max_q=3
m=12
seasonal=false
d=1
trace=true
suppress_warnings=true
stepwise=true

[es]
smoothing_level=0.8
optimized=false