# 基于miniconda生成基础镜像
FROM digit-force-docker.pkg.coding.net/ai-platform/base-images/miniconda3
RUN conda create -n python39 python=3.9 -y
RUN source activate && conda activate python39
COPY requirements-python39.txt /tmp/requirements.txt
# 安装python依赖包
RUN . ~/.bashrc && conda activate python39 && pip --default-timeout=1000 install --ignore-installed --use-deprecated=legacy-resolver -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 执行命令如下
# docker build -t digit-force-docker.pkg.coding.net/ai-platform/base-images/python:3.9 -f Dockerfile-python39 .