# 基于miniconda生成基础镜像
FROM continuumio/miniconda3:4.11.0
# 添加apt的阿里源
COPY dockerfiles/debian-10-sourcelist /etc/apt/sources.list
# 添加requirements-base的依赖
COPY dockerfiles/requirements-base.txt /tmp/requirements.txt
# 安装python依赖包
RUN pip --default-timeout=1000 install --ignore-installed --use-deprecated=legacy-resolver -r /tmp/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 执行命令如下
# docker build -t miniconda3-base -f Dockerfile-base .