[spark]
pyspark_driver_python='/data/ibs/anaconda3/bin/python'
pyspark_python='/data/ibs/anaconda3/bin/python'
app_name='time_series_predict'
master='yarn'
spark.yarn.queue='default'
spark.executor.instances='10'
spark.executor.memory='16g'
spark.executor.cores='2'
spark.driver.memory='8g'
spark.driver.maxResultSize='2g'
spark.default.parallelism='600'
spark.network.timeout='60s'
spark.sql.adaptive.enabled='true'
spark.sql.adaptive.join.enabled='true'
spark.sql.adaptive.shuffle.targetPostShuffleInputSize='128000000'
spark.dynamicAllocation.enabled='true'
spark.dynamicAllocation.minExecutors='1'
spark.shuffle.service.enabled='true'
spark.sql.sources.partitionOverwriteMode='dynamic'
hive.exec.dynamici.partition='true'
hive.exec.dynamic.partition.mode='nonstrict'
hive.exec.max.dynamic.partitions='10000'

[hdfs]
hosts='bigdata-server-08:9870'
user_name='root'

[mysql]
mysql_host="172.21.32.86"
mysql_port=3306
mysql_user="digitforce_arch"
mysql_password="arch123456"

[hive]