[params]
col_key = ['shop_id','goods_id']#商品分类所用的主字段
w_tail=3
w_ls=90
threshold_count=1
threshold_proportion=0.15
threshold_sales=14
col_time = 'sdt'
col_qty = 'th_y'
partition_list = ['1004','1228']
input_partition_name = 'shop_id'
output_partition_names = ['shop_id']
config_columns = ['storage_life','sale_period','standard','is_new','sale_days']
item_config_table = "f'{db_dev}.{pre_table_name}_item_config'"
col_sku_category = 'sales_category' #sku分类字段
input_table = "f'{db_dev}.{pre_table_name}_sales_boxcox'"
output_table = "f'{db_dev}.{pre_table_name}_sales_classify'"
mode_type = 'sp'
sdate = ''
edate = ''

